# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ppp_ping_pb2 as ppp__ping__pb2


class PPPsubPingServeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SubmitWillPing = channel.unary_unary(
        '/PPPsubPingServe/SubmitWillPing',
        request_serializer=ppp__ping__pb2.DoPingRequest.SerializeToString,
        response_deserializer=ppp__ping__pb2.DoPingReply.FromString,
        )


class PPPsubPingServeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SubmitWillPing(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PPPsubPingServeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SubmitWillPing': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitWillPing,
          request_deserializer=ppp__ping__pb2.DoPingRequest.FromString,
          response_serializer=ppp__ping__pb2.DoPingReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PPPsubPingServe', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
