#! /bin/sh
### BEGIN INIT INFO
# Provides:          data_collector
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      6
# Short-Description: Execute the data_collector command.
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin


do_stop () {
    ps -ef | grep "/opt/nokia/rtm/data_collector/main/data_collector_daemo.py" | grep -v "grep" | awk '{print $2}'|xargs kill  > /dev/null 2>&1 &
    ps -ef | grep "/opt/nokia/rtm/data_collector/main/data_collector.py" | grep -v "grep" | awk '{print $2}'|xargs kill  > /dev/null 2>&1 &
    sleep 1;
    pid=$(ps -ef | grep "/opt/nokia/rtm/data_collector/main/data_collector.py" | grep -v "grep" | awk '{print $2}')
    if [ ! -n "$pid" ] ; then
        echo "Stop data collector ok"
    else
        echo "Stop data collector failed. Please retry ...."
    fi
}

do_start () {
    export MIBS="ALL"
    count=$(cat "/opt/nokia/rtm/data_collector/config/rtm.cfg" |grep "process_number"|awk -F '=' '{print $2}')
    count="$(echo -e "${count}" | sed -e 's/^[[:space:]]*//')"
    if [ "$count" = "" ]
    then
        count=1
    fi

    for ((i = 0 ; i < $count ; i++));
    do
        echo $i;
        /opt/nokia/rtm/data_collector/main/data_collector.py $count $i  > /dev/null 2>&1 &
    done

    pid=$(ps -ef | grep "/opt/nokia/rtm/data_collector/main/data_collector.py" | grep -v "grep" | awk '{print $2}')
    sleep 1;
    if [ ! -n "$pid" ] ; then
        echo "Start data collector failed. Please retry ...."
    else
        echo "Start data collector ok"
    fi
    /opt/nokia/rtm/data_collector/main/data_collector_daemo.py > /dev/null 2>&1 &
    pid=$(ps -ef | grep "/opt/nokia/rtm/data_collector/main/data_collector_daemo.py" | grep -v "grep" | awk '{print $2}')
    sleep 1;
    if [ ! -n "$pid" ] ; then
        echo "Start data collector dameo failed. Please retry ...."
    else
        echo "Start data collector dameo ok"
    fi
}

case "$1" in
  start)
    do_start
	# No-op
	;;
  restart|reload|force-reload)
    do_stop
    do_start
	;;
  stop)
    do_stop
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
